//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24DH113309_MyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingAddress
    {
        public int AddressID { get; set; }
        public int CustomerID { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Ward { get; set; }
        public string DetailAddress { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
